# Generated by Django 4.1.7 on 2023-03-21 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pickup_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='pickup_order',
        ),
    ]
