# Generated by Django 4.2.1 on 2023-07-20 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickup_app', '0002_remove_cartitem_pickup_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='printed_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
