# Generated by Django 4.2.1 on 2023-11-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickup_app', '0004_pickuporder_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuporder',
            name='payment_method',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
