# Generated by Django 4.2.1 on 2023-11-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickup_app', '0005_pickuporder_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuporder',
            name='cart_snapshot',
            field=models.TextField(blank=True, null=True),
        ),
    ]
