# Generated by Django 4.2.1 on 2023-11-14 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaymentMethod',
            new_name='PayMethod',
        ),
    ]
