# Generated by Django 4.2.1 on 2023-11-15 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_rename_paymentmethod_paymethod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='category',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='payment_method',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='PayMethod',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
