# Generated by Django 4.0 on 2023-03-06 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant_app', '0001_initial'),
        ('delivery_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant_app.product'),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='delivery_app.deliverycustomer'),
        ),
        migrations.AddField(
            model_name='deliverycartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_cart_items', to='delivery_app.deliverycart'),
        ),
        migrations.AddField(
            model_name='deliverycartitem',
            name='delivery_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_cart_items', to='delivery_app.deliveryorder'),
        ),
        migrations.AddField(
            model_name='deliverycartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_product', to='restaurant_app.product'),
        ),
        migrations.AddField(
            model_name='deliverycart',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery_app.deliverycustomer'),
        ),
        migrations.AddField(
            model_name='deliverycart',
            name='delivery_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_carts', to='delivery_app.deliveryorder'),
        ),
    ]
