# Generated by Django 4.1.7 on 2023-03-22 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0002_alter_deliverycart_delivery_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverycartitem',
            name='delivery_order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_cart_items', to='delivery_app.deliveryorder'),
        ),
    ]
