# Generated by Django 4.0 on 2023-03-10 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0002_rename_table_booking_table_id'),
        ('delivery_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverycartitem',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_cart_items', to='delivery_app.deliverycart'),
        ),
        migrations.AlterField(
            model_name='deliverycartitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_product', to='restaurant_app.product'),
        ),
        migrations.AlterField(
            model_name='deliveryproduct',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant_app.product'),
        ),
    ]
