# Generated by Django 4.1.7 on 2023-03-23 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0003_alter_deliverycartitem_delivery_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverycartitem',
            name='cart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_cart_items', to='delivery_app.deliverycart'),
            preserve_default=False,
        ),
    ]
