# Generated by Django 4.0 on 2023-04-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0005_alter_deliverycartitem_delivery_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverycustomer',
            name='street',
            field=models.CharField(max_length=30),
        ),
    ]
