# Generated by Django 4.0 on 2023-04-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0007_alter_deliverycustomer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Наличные'), ('credit_card', 'Кредитная карта')], max_length=12, null=True),
        ),
    ]
