# Generated by Django 4.0 on 2023-04-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0008_deliveryorder_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverycustomer',
            name='intercom_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
