# Generated by Django 4.2.1 on 2023-07-20 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0011_alter_deliverycustomer_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverycartitem',
            name='printed_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
