# Generated by Django 4.0 on 2023-09-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0012_deliverycartitem_printed_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('our_courier', 'Наша Курьер'), ('solo', 'Соло')], max_length=50, unique=True)),
            ],
        ),
    ]
