# Generated by Django 4.0 on 2023-09-22 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0013_courier'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='courier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='delivery_app.courier'),
        ),
    ]
