# Generated by Django 4.2.1 on 2023-09-26 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0014_deliveryorder_courier'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='delivery_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courier',
            name='delivery_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='courier',
            name='delivery_city',
            field=models.CharField(blank=True, choices=[('חיפה', 'Хайфа'), ('נשר', 'Нэшер'), ('טירת כרמל', 'Тира'), ('כפר גלים', 'Кфар Галим'), ('קריית חיים', 'Кирият Хаим'), ('קריית אתא', 'Кирият Ата'), ('קריית ביאליק', 'Кирият Биалик'), ('קריית ים', 'Кирият Ям'), ('קריית מוצקין', 'Кирият Моцкин')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='courier',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Наличные'), ('credit_card', 'Кредитная карта')], max_length=12, null=True),
        ),
        migrations.CreateModel(
            name='CourierDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_address', models.CharField(max_length=255)),
                ('delivery_city', models.CharField(choices=[('חיפה', 'Хайфа'), ('נשר', 'Нэшер'), ('טירת כרמל', 'Тира'), ('כפר גלים', 'Кфар Галим'), ('קריית חיים', 'Кирият Хаим'), ('קריית אתא', 'Кирият Ата'), ('קריית ביאליק', 'Кирият Биалик'), ('קריית ים', 'Кирият Ям'), ('קריית מוצקין', 'Кирият Моцкин')], max_length=50)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Наличные'), ('credit_card', 'Кредитная карта')], max_length=12)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery_app.courier')),
            ],
        ),
    ]
