# Generated by Django 4.2.1 on 2023-09-26 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0015_courier_delivery_address_courier_delivery_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Наличные'), ('card', 'Картой')], max_length=12, null=True),
        ),
    ]
