# Generated by Django 4.2.1 on 2023-09-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0016_deliveryorder_total_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryorder',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Наличные'), ('credit_card', 'Кредитная карта')], max_length=12, null=True),
        ),
    ]
