# Generated by Django 4.2.1 on 2023-09-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0017_alter_deliveryorder_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='name',
            field=models.CharField(choices=[('our_courier', 'Наш Курьер'), ('solo', 'Соло')], max_length=50, unique=True),
        ),
    ]
