# Generated by Django 4.2.1 on 2023-11-14 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0018_alter_courier_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='delivery_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
