# Generated by Django 4.2.1 on 2023-11-22 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0019_deliveryorder_delivery_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
