# Generated by Django 4.2.1 on 2023-11-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0020_alter_courier_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='name',
            field=models.CharField(choices=[('solo', 'Solo'), ('our_courier', 'Стас')], max_length=50),
        ),
    ]
