# Generated by Django 5.0.1 on 2024-06-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0021_alter_courier_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='transaction_created',
            field=models.BooleanField(default=False),
        ),
    ]
