# Generated by Django 4.0 on 2023-03-06 16:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name_rus', models.CharField(max_length=100, verbose_name='Название блюда (рус.)')),
                ('product_name_heb', models.CharField(max_length=100, verbose_name='שם מנה (עברית)')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('product_img', models.ImageField(upload_to='product_images/')),
                ('category', models.CharField(choices=[('first_dishes', 'first_dishes'), ('meat_dishes', 'meat_dishes'), ('bakery', 'bakery'), ('khinkali', 'khinkali'), ('khachapuri', 'khachapuri'), ('garnish', 'garnish'), ('grill_meat', 'grill_meat'), ('dessert', 'dessert'), ('soups', 'soups'), ('salads', 'salads'), ('sales', 'sales'), ('delivery', 'delivery'), ('drinks', 'drinks'), ('soft_drinks', 'soft_drinks'), ('beer', 'beer'), ('wine', 'wine'), ('vodka', 'vodka'), ('cognac', 'cognac'), ('whisky', 'whisky'), ('dessert_drinks', 'dessert_drinks')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('delivery_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_id', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('is_booked', models.BooleanField(default=False)),
                ('is_ordered', models.BooleanField(default=False)),
                ('reserved_date', models.DateField(blank=True, null=True)),
                ('reserved_time', models.TimeField(blank=True, null=True)),
                ('num_of_people', models.IntegerField(blank=True, null=True)),
                ('order_time', models.DateTimeField(blank=True, null=True)),
                ('are_guests_here', models.BooleanField(default=False)),
                ('capacity', models.IntegerField()),
                ('active_order', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['table_id'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='active', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('card', 'Card')], max_length=10, null=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='restaurant_app.table')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved_date', models.DateField()),
                ('reserved_time', models.TimeField()),
                ('num_of_people', models.IntegerField()),
                ('are_guests_here', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='restaurant_app.table')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantity')),
                ('phone_number', models.CharField(max_length=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='restaurant_app.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='restaurant_app.product')),
            ],
            options={
                'unique_together': {('order', 'product')},
            },
        ),
    ]
