# Generated by Django 4.0 on 2023-03-10 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='table',
            new_name='table_id',
        ),
    ]
