# Generated by Django 4.0 on 2023-03-10 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0002_rename_table_booking_table_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='table_id',
            new_name='table',
        ),
    ]
