# Generated by Django 4.1.7 on 2023-03-25 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0004_alter_order_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('first_dishes', 'first_dishes'), ('meat_dishes', 'meat_dishes'), ('bakery', 'bakery'), ('khinkali', 'khinkali'), ('khachapuri', 'khachapuri'), ('garnish', 'garnish'), ('grill_meat', 'grill_meat'), ('dessert', 'dessert'), ('soups', 'soups'), ('salads', 'salads'), ('sales', 'sales'), ('delivery', 'delivery'), ('drinks', 'drinks'), ('soft_drinks', 'soft_drinks'), ('beer', 'beer'), ('wine', 'wine'), ('vodka', 'vodka'), ('cognac', 'cognac'), ('whisky', 'whisky'), ('dessert_drinks', 'dessert_drinks'), ('own_alc', 'own_alc')], max_length=50),
        ),
    ]
