# Generated by Django 4.1.7 on 2023-03-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0005_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='alcohol',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='extras',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='portion',
            field=models.IntegerField(choices=[(1, '180'), (2, '200')], default=1),
        ),
        migrations.AddField(
            model_name='booking',
            name='premium_wine',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='prepayment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
