# Generated by Django 4.1.7 on 2023-04-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0008_product_additional_option_1_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='additional_option_1_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='additional_option_2_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='additional_option_3_price',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='printed',
            field=models.BooleanField(default=False),
        ),
    ]
