# Generated by Django 4.1.7 on 2023-04-18 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0009_remove_product_additional_option_1_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='alcohol',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='extras',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='portion',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='premium_wine',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='prepayment',
        ),
    ]
