# Generated by Django 4.0 on 2023-05-03 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0011_orderitem_printed_quantity_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
