# Generated by Django 4.2.1 on 2023-05-23 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0014_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='table_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
