# Generated by Django 4.2.1 on 2023-08-30 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0019_tipgoal'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='guests_did_not_arrive',
            field=models.BooleanField(default=False),
        ),
    ]
