# Generated by Django 4.2.1 on 2023-09-14 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant_app', '0021_remove_tip_user_tip_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tip',
            name='users',
        ),
        migrations.CreateModel(
            name='TipDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant_app.tip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
