# Generated by Django 4.0 on 2023-09-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0027_alter_product_printer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='printer',
            field=models.CharField(choices=[('print80', 'Бар'), ('Printer80', 'Мал Кухня'), ('Printer80-2', 'Бол Кухня')], default='kitchen_1', max_length=50, verbose_name='Принтер'),
        ),
    ]
