# Generated by Django 4.2.1 on 2023-10-01 14:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant_app', '0028_alter_product_printer'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tipdistribution',
            unique_together={('tip', 'user')},
        ),
    ]
