# Generated by Django 4.2.1 on 2023-11-12 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0040_category_paymentmethod_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('action', models.CharField(choices=[('decrease', 'Decrease Quantity'), ('delete', 'Delete Item')], max_length=10)),
                ('change_time', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant_app.order')),
            ],
        ),
    ]
