# Generated by Django 4.2.1 on 2023-11-12 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0041_orderchangelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='card_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cash_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
