# Generated by Django 4.2.1 on 2023-11-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0042_order_card_amount_order_cash_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('card', 'Card'), ('mixed', 'Mixed')], max_length=10, null=True),
        ),
    ]
