# Generated by Django 4.2.1 on 2023-11-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0047_transaction_card_amount_transaction_cash_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank Transfer'), ('CARD', 'Card'), ('MIXED', 'Mixed')], max_length=5),
        ),
    ]
