# Generated by Django 4.2.1 on 2023-11-20 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0048_alter_paymentmethod_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
