# Generated by Django 4.2.1 on 2023-11-20 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0050_alter_transaction_added_date_alter_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='max_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
