# Generated by Django 4.2.1 on 2023-11-23 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0052_order_is_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_bill_printed',
            field=models.BooleanField(default=False),
        ),
    ]
