# Generated by Django 5.0.1 on 2024-03-03 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0056_orderitem_is_delivered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderchangelog',
            name='action',
            field=models.CharField(choices=[('add', 'Add Item'), ('decrease', 'Decrease Quantity'), ('delete', 'Delete Item')], max_length=10),
        ),
    ]
