# Generated by Django 5.0.1 on 2024-03-03 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0061_alter_orderchangelog_action'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderchangelog',
            options={'ordering': ['change_time']},
        ),
    ]
