# Generated by Django 5.0.1 on 2024-06-01 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0063_orderchangelog_changed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='card_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='cash_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
