# Generated by Django 5.0.1 on 2024-06-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0066_alter_order_created_by_alter_tipgoal_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_limit',
            field=models.BooleanField(default=False, verbose_name='Лимитированный продукт'),
        ),
        migrations.AddField(
            model_name='product',
            name='limit_quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество лимита'),
        ),
    ]
