# Generated by Django 5.0.1 on 2024-06-05 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0067_product_has_limit_product_limit_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='printer',
            field=models.CharField(choices=[('print80', 'Бар'), ('Printer80', 'Мал Кухня'), ('Printer80-2', 'Бол Кухня')], default='print80', max_length=50, verbose_name='Принтер'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена продукта'),
        ),
    ]
