# Generated by Django 5.0.1 on 2024-06-06 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0070_alter_message_chat'),
    ]

    operations = [
    ]
