# Generated by Django 5.0.1 on 2024-06-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0071_auto_20240606_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transaction_created',
            field=models.BooleanField(default=False),
        ),
    ]
