# Generated by Django 5.0.1 on 2024-06-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0072_order_transaction_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_available_for_delivery',
            field=models.BooleanField(default=False, verbose_name='Доступен для доставки'),
        ),
    ]
